// <auto-generated />
using BlazorPostgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorPostgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004235151_dbProdutosV1")]
    partial class dbProdutosV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorPostgres.Models.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("BlazorPostgres.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("categoriaID")
                        .HasColumnType("integer");

                    b.Property<string>("codigo_barra")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("estoque")
                        .HasColumnType("integer");

                    b.Property<decimal>("preco_custo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("preco_custo_medio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("preco_venda_prazo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("preco_venda_vista")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("categoriaID");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("BlazorPostgres.Models.Produto", b =>
                {
                    b.HasOne("BlazorPostgres.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaID");

                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
